# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

relative_permalinks: false
plugins: [jekyll-paginate]
# Setup
title:               PyData Gandhinagar
tagline:             Official meetup of PyData Gandhinagar
description:         
url:                 
baseurl:             ''
paginate_path: "/blog/page:num/"
paginate:            5
future: true

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
